print ("primer cambio")
print ("segundo cambio")
print ("tercer cambio")
print ("cuarto cambio")

print ("prueba flujo de trabajo en rama master")
print ("segunda prueba de flujo")
print ("prueba error")
print ("utlimo cambio en stash")
print ("utlimo cambio en stash 1")
print ("nuevo cambio")
print ("nuevo cmabio")
print("dcdd")
print ("otro")